---
Name: sesbouncehandlermodelascontrollerroutes
After: cms/routes#modelascontrollerroutes
---
SilverStripe\Control\Director:
  rules:
    'ses-bounce-handler': 'WSE\SESBounceHandler\Controllers\SESBounceController'
